# Generated by Django 5.2 on 2025-05-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="adres_kodu",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nature.address",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="current_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nature.user",
            ),
        ),
    ]
