# Generated by Django 5.2 on 2025-05-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0002_property_adres_kodu_alter_property_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="adres_kodu",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
